apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:zcXa4ayO9DO1Ua5SCeke0Zy2C+rTuEaskxrviCspXskAPWM2Tpu2CK7S9V+U/86dJsGKzGMMqRMiu1NHuHc7dZfZkTiUTPTdMfYPNOI1XL/aRfW5eQSY6YHYtq1jMlvsso2pBcQPQ6G7sHBWguiEXoF2ZB1iVvokGjSQE2f7xLCkKMqcF5QVwlgch0L4M8tkNPzLbbj9s6MmN36c0Y3M0OI5bBeQQ9D8g5RwZc/H75yAilogBfgojaEnEGOdbcqJD0v/61CLXV4JChkfOD1ZcNAsnOst+oltaIPGK3onaFni9A9WWvZQi+0KIN3NF/m8Vr5lM0P+OxxgMYb96MhjJn19I5Px6opMk+7shlG6mn6KvnKcXKZwqhSZz/+dv2fk+MhL42qEA0q5rpfYYutCAhJkobBM6ivRqy/14Z3/43rQ+cQp2I/Lsdg7K1v/pb64BXRpvnqp2Ls1eDXFAwWm4Y1Ru6sgWwfjpcTqfMBGp2KrvgDuTgNudkaG7Sc/O2mOGTS/u6QtlZhoXUV++RsQHhZ7osHT1BcYE/1/ywdkvy2uBiYWjoTIlDbOdYhT8lvxU7OfznTHEUE5ikmo41DHbWLJDJUKDxCZEclFZGVOkMsQNiaCU5kavmQCelOoHVw=,iv:D/1P8FXABsZ74FkJkAnAiqsQVWxJvPStgfp6TPMh38M=,tag:yLlJVGrGQ8jje98Jg33PBQ==,type:str]
    vvisveswaran.tmpl: ENC[AES256_GCM,data:ec7FY3j1LpvpXlzJGmfBi0CnT2iU77ugkI+euhtgAdcqqLTYRDRWTnV/SeAwcHiJVTTQrPwXE6U71eg4I9HdWkJWqBywfGxPUV/Tvw/n+WuoARNEy3QSppZKF+LBGp4JCBsWcBKy/B5vKz8Ssechhg3r2n/ZjfL6AOLK/HpoWU7h/Lbo36yZYvGKwmkaz7YSu4HraLUhM2xqd1BL9WwL1fV7w9ymMyiAsa9MYODlPSwRVpfwS0e2+sP4KfPYHO7KQ5Gm2gEyJ/BBZUKHpPNX7ihtOC+vnM5ErGmF0MOJJXSJsS3UtqPJsNGH/iCe0xKgORvWTTOkG9n1mdddgkcevMaOlMq7uXqmb80RNRrQUHbg6GJfaREwUjjRSt6kWxgwH6CSK4aQvjv33y6ANy+LgMUWtuoPqARNQYJQ6gzymxIrqknD5mZ9QGwZ++ApuDiYPFq3K2XwebMkaHwOfW/emOPvLzd2It1w2CwQq8sQXE6W7AzVy6Z0zHBWxgRkqK17flW8dd4FsfmjRdLe+z/KMR4ETtIctsv1FS9e3oyU5ZZq+Usoc3H+zc77/7DN65iVBsM1SIrSpJFfHAhEg1tBvmJpvt+93OQpcbGjh72+wiBtrajCnaLpk6yV1tCyMD1hPP87PKvxTvaqqICsrdO1CyuKYCfMNLhQkEK/+gJEtHmp+0gXDx2Q1NIDIvnOk/501tNCmuUdB1mF8ZofYe4MJ5WftwEWq47HBXu49N3SZmTCnQC567dDmTC1IRuL5t487rbbsrduE0r63Rj1C1jlljWio0a4CCtV9WPfMOUK/BKMXTo=,iv:cDGXoTgA7DEtVX/HFiu3GIygn2mT486R04INjOdE5Zw=,tag:ORUlmTvyZzqhbMx2JICaRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jc73zfxxcfclqrpvy7qfdlnd5t50j8sthsl3m4xndx2vnaz6092slrvn98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YTQrVDJ5WXE1UWppeW1B
            OU0xcFRySkRIek4wWjlHM0dkZHp5cHpkanpFCnA5WWZCUWE2Y2tOYUZ2MkhBekhX
            bmVRZXJLVjUzaWhjV3c3dE01djF5VjgKLS0tIEliMUU3RlRaY3pCbnp3ZTJCZjJw
            dnRsSVR0SzNUTXVyUXQzWW91a1lxeU0K0r9+z1pZME0S/+7imZw2eHnTkHTiOriR
            oIY0wTqL1dtM0eYioD75UO7ugg4A7+EKQjB5XXsuVgIRJSH3WO9vXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T08:00:00Z"
    mac: ENC[AES256_GCM,data:gL1M2D14tcgu0lOWv0m0cdT1UuRirQBwr3IxzoZGp669ugOsyFcNgwtnEhWA/EINRSmkPTRcxEgALLMLaF9NDGxnCqzakB7WnHaT6ATJZxw06RujG3Uj8novVZbsy7X4WnGZ94FZnvWYnQTGy4N5bVJ04CqclZsDErkabMMwPK8=,iv:o5tKoFSbVnrVxKVuu+/L1tlUCFmJLHzh+1VPdQ7YICk=,tag:RE0y1zdpVx9O/4buZHoFNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
