apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:TSw6ZYVqJaxrwZWxdl1Zfp+BkpjLo2NElDR2nY0uZ9/zAPXCCjCX+bjRUWo0ZBl7jknScWSb20/65NCrVualCoRv/BFHOYjUDh4Pcw6Np1dvz/2acpwwxcFZT3h3wG7FHi3vUhJbEvX8Sk36jYj4hV9sVY1/7wADkhudUZVGV1uU6NshDXzLCKm35aiBaTL070DJaTfFc3ZVN5aXG9wadVnX22XZwpZG82lGMs5RHD3I9ReVFlMInF/uW5FiMSctsbPy3uIV5hXEBisxIrBK7bb1dVq/Y4DBeaAT4lscP4lsAZanPGSYZivx7H3KiqtCzFwMOw/UGqcOrBVJqDuMX5zjN8e+a2o1a824GaadCN6Y3xHvAtrNGBQzL/d2ryE5LGFQylfVyZh4o3gUWbfpJe7e1nYRwXKRzHYPlUKxXCkFD2KAeVe6xn5AZWgFKQlBN0z8SmKOCYbxOIOIgn8mNSGbiBMOZ0RRZZo/IhHX7l2s,iv:KsXb2/ngUMRaDitHYV/Fufjica5PsXVSu0o+EhBOogQ=,tag:XNSNnb37QFvOGMwmK8MRGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jc73zfxxcfclqrpvy7qfdlnd5t50j8sthsl3m4xndx2vnaz6092slrvn98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweGxuTGc5Nm1WOU12ejNy
            MmJtQXJJOHE4emppUm5nTFlmV3VDWGtObTNnCk41Z0pQRXJHdnEyOHd0c0htbVU0
            OTl6VGdzKzZWaVFrd3J0bDJjd3NNdzgKLS0tIHpFYllXN0V2S1ZQU3BFT1JIN1BT
            U2UvY2h2cUN2eGhLWGtsZDlFeUxud1EKPkMuWrk0W0x55jw0LvYutmof6fHf2OjO
            Qm5s5kIKJY4I5CtEpJ5WASMLxwRASOELC2SCaQargzB6eu+Yf71UMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T04:01:30Z"
    mac: ENC[AES256_GCM,data:CuKR3PCVHbzMnnH3K9qYMRxnrDxNKmveo/WxxnV+/BAE7O2fIrXahBqlZwJ0cXUV7qqas8j2jPDQLzJMj2wuhf+MVgdWvtRu2ufdNwU+Xc1v7T476ehj6kHjMrKAYLbgMUXV9poHkQA+qycNIVraGdwUBGKPAjO8mDn/75wnO3I=,iv:XRi6QrJjVq4MQGfHbtAw9CnZJcQ/lYcboNOI25KMFIs=,tag:znmlJ9iTyFzruBaB2DIVNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
