apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:aFYG6dCzwaS99A==,iv:en8Po1+qOWZugZWNbsgPUDXSAuAAH3CjK5jQWtTpg7E=,tag:lv8p3pfNKzCeW8AHdyklHw==,type:str]
    admin-password: ENC[AES256_GCM,data:x88bOO2ZMwK1nek=,iv:kdC7E7pEs/tVb1E8gUokqAuUUIz36NX83kY7J3n/L0I=,tag:GF95cutOCArWB8goCcb9Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jc73zfxxcfclqrpvy7qfdlnd5t50j8sthsl3m4xndx2vnaz6092slrvn98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SkNSL2c4KzFNMDYreFpj
            ZGFwVjdkM0pOcmxFdUx1WU5kMkVCeDVFZkg4CkZhaFFoY29naXF2akxaVG0xWWxo
            bmtvVUFCMk9UUTdBUHdscTNVaVNLSEUKLS0tIGdXTUg2SHRJSzIvbTNrdjFUWmhO
            UFo3NEpDOUEyeDY4QTloclcrMElGUXMKZbr7cY6ryS5dFQO71SeHh+5PHkkl7pQg
            +5MGmiy7LYs1yDJzAloBzJxbByy5W3LPFNmlK3DlZRoecfilxhKQog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T12:18:56Z"
    mac: ENC[AES256_GCM,data:d1uVCSawoRwY1qdqqX6XaycDHDrq1klPxRBMH/6K3KftjhwjbhqTJc298QvudH6yTx4xw1+MezJiLL0F+3Bh5Ekcm7gXzkuoG/t5A+GfDMDvaoGr2VLk2H/tPY1DUdeEtKIgQPmFtcHAd0MYfmLdMzyXz+HXUiHCL5CGlPjhOdk=,iv:9FEsl7C/t5xQ7+3XcpSKuX1FdZJiHbqOG1sEwqHd1qg=,tag:vHuQMkp8gwJhW5WU9QO8ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
